version: '3.1'

networks:
    lamp-network:
    
services:
    web-server:
        image: krishnakumarkp/blog-php-secret
        ports: 
            - "80:80"
        networks:
            - lamp-network
        secrets:
            - db_host
            - db_name
            - db_user
            - db_password
        depends_on:
            - blog-mysql
        deploy:
            replicas: 2
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
                condition: on-failure
    blog-mysql:
        image: krishnakumarkp/blog-mysql
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
        volumes:
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - lamp-network
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager]
secrets:
    db_host:
        file: ./db_host.txt
    db_name:
        file: ./db_name.txt
    db_user:
        file: ./db_user.txt
    db_password:
        file: ./db_password.txt
volumes:
    persistent: